Repository puppetlabs/puppetlabs-puppet_agent, pull requests merged in 2024-09, with the labels that each got.

#711 sh tasks: Run with set -e
  tasks/install_shell.sh
  tasks/version_shell.sh
Labels: bug

#713 install support download with apt-helper
  tasks/install_shell.sh
Labels: enhancement

#736 Test updates
  task_spec/spec/acceptance/init_spec.rb
Labels: maintenance
